### ISSUE TITLE
Library has inadequate documentation in the docs directory

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-options#34]
**Is your change request related to a problem? Please describe.**
As described in the [documentation section of the Library Guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#documentation), Contributors libraries are expected to have some documentation in the docs directory -- specifically, a changelog and at least a short tutorial that expands on the quick start in the README.

This library currently doesn't have any extra documentation in the docs directory. It would be helpful to explain this library from first principles, noting what problems arise when trying to solve this and how one can solve those problems. Additionally, adding a Cookbook recipe for this repo would be nice.

**Describe the solution you'd like**
The changelog needs to be updated for at least the most recent release (we can then start curating it going forward) and at least a short tutorial needs to be added to the docs directory, or other documentation [as described in this Divio article](https://documentation.divio.com).

The [argonaut-codecs docs directory](https://github.com/purescript-contrib/purescript-argonaut-codecs/tree/master/docs) has a good example of expanded documentation for a Contributor library. But it would even be useful to add something considerably smaller and shorter to this library.

**Additional context**
See the [Governance repository](https://github.com/purescript-contrib/governance) for more information about requirements in the Contributors organization.

**Comment by thomashoneyman** [comment]
As a quick note, there's some lengthy documentation included as a module header here:
https://github.com/purescript-contrib/purescript-options/blob/main/src/Data/Options.purs

This could be adapted / moved to the docs directory.

**Comment by hdgarrood** [comment]
I think putting documentation inside the code (like it is there) is preferable, because that way it will show up on Pursuit.

**Comment by thomashoneyman** [comment]
I also like documentation in the code, because it shows up on Pursuit, and I think it's underutilized.

For this library, which is very small, perhaps it would be better to not have a documentation directory at all and instead link to the module from the main README.

**Comment by JordanMartinez** [comment]
Sounds sensible to me.

**Comment by JordanMartinez** [comment]
@thomashoneyman If I delete the `docs` folder, it'll remove the `CHANGELOG.md` file as well. I agree with Harry that that file should be in the root folder rather than in the docs folder.

**Comment by thomashoneyman** [comment]
Let's go for it. We can move the CHANGELOG and CONTRIBUTING file locations (we'll also need to update the relative links to these files in other .md files)
